CAFapi/caf-dependency-management-bom

pom.xml

https://portal.digitalsafe.net/browse/SCMOD-8829

SCMOD-8829: Updates for worker-archive-cleanup

---

pom.xml

https://portal.digitalsafe.net/browse/SCMOD-8829

SCMOD-8829: Autoscaler changes

---

pom.xml

https://portal.digitalsafe.net/browse/SCMOD-8829

SCMOD-8829: Changes for Bulk Indexer

---

pom.xml

https://portal.digitalsafe.net/browse/SCMOD-8829

SCMOD-8829: Centralize dependency management

---

pom.xml

Remove dependency on inner-source component

---

pom.xml

https://portal.digitalsafe.net/browse/SCMOD-10362

SCMOD-10362: GraalVM JS dependencies

---

pom.xml

https://portal.digitalsafe.net/browse/SCMOD-11144

SCMOD-11144: Upgrade PostgreSql to 42.2.18

---

pom.xml

https://portal.digitalsafe.net/browse/SCMOD-11144

SCMOD-11144: Upgrade json-schema-core to 1.2.14

---

pom.xml

https://portal.digitalsafe.net/browse/SCMOD-11813

SCMOD-11813: Downgrading json-schema-core

---

pom.xml

A pre-release step as we cannot guarantee that this is not a breaking change.

Updated POM version to 2.0.0-SNAPSHOT

---

pom.xml

https://portal.digitalsafe.net/browse/SCMOD-11994

SCMOD-11994: Update worker-document to latest version

---

pom.xml
release-notes-3.1.0.md

https://portal.digitalsafe.net/browse/SCMOD-13868
Updated worker-document version to pull in new worker-store-http module from worker-framework.

SCMOD-13868: Update worker-document version

---

pom.xml

https://portal.digitalsafe.net/browse/SCMOD-9678

SCMOD-9678: Update Flyway version to latest

---

pom.xml

https://portal.digitalsafe.net/browse/SCMOD-12113

SCMOD-12113: Update swaggerUI

---

pom.xml

https://internal.almoctane.com/ui/?p=131002%2F6001&idpId=https%3A%2F%2Fauthenticate.microfocus.net%2Fnidp%2Fsaml2%2Fmetadata#/team-backlog/stories

Migrating to new logger version

---

pom.xml

https://internal.almoctane.com/ui/entity-navigation?p=131002/6001&entityType=work_item&id=509054

US509054: Upgrade PostgreSQL JDBC Driver

---

pom.xml
release-notes-3.3.0.md

https://internal.almoctane.com/ui/entity-navigation?p=131002/6001&entityType=work_item&id=517060

Update pom.xml with latest version '8.5.13' of flyway

---

pom.xml
release-notes-3.3.0.md

https://internal.almoctane.com/ui/entity-navigation?p=131002/6001&entityType=work_item&id=572083

US572083: Update snakeyaml version to 1.32

---

release-notes-3.3.0.md

https://internal.almoctane.com/ui/entity-navigation?p=131002/6001&entityType=work_item&id=613096

US613096: Release caf-dependency-management-bom

---

pom.xml

https://internal.almoctane.com/ui/entity-navigation?p=131002/6001&entityType=work_item&id=627175

D627175: Update downstream dependencies

---

pom.xml

https://internal.almoctane.com/ui/entity-navigation?p=131002/6001&entityType=work_item&id=663092

US663092: worker-document release downstream dependency

---

pom.xml

https://internal.almoctane.com/ui/entity-navigation?p=131002/6001&entityType=work_item&id=687007

US687007: CVE-2021-42392: Remove h2

---

pom.xml

Ticket: https://internal.almoctane.com/ui/entity-navigation?p=131002/6001&entityType=work_item&id=868108

US868108: Update Copyright statements to 2024

---

pom.xml

https://internal.almoctane.com/ui/entity-navigation?p=131002/6001&entityType=work_item&id=1002065

US1002065: Update copyrights statements to 2025 
